export const WALLET_TX_HISTORY = 'WALLET_TX_HISTORY';
export const WALLET_NET_WORTH = 'WALLET_NET_WORTH';
export const WALLET_STATS = 'WALLET_STATS';
export const WALLET_TOKEN_HOLDINGS = 'WALLET_TOKEN_HOLDINGS';
export const WALLET_NFT_HOLDINGS = 'WALLET_NFT_HOLDINGS';
